tap "nikitabobko/tap"

brew "chezmoi"
brew "atuin"
brew "fd"
brew "fzf"
brew "gh"
brew "herdr"
brew "jq"
brew "neovim"
brew "python"
brew "ripgrep"
brew "shellcheck"
brew "starship"
brew "tmux"
brew "tree-sitter-cli"
brew "zoxide"

cask "nikitabobko/tap/aerospace"
cask "ghostty"
cask "cloudflare-warp"
cask "hammerspoon"
cask "font-jetbrains-mono-nerd-font"
cask "slack"
cask "visual-studio-code"
