#!/usr/bin/env bash
set -euo pipefail

output_height=$(swaymsg --raw --type get_outputs \
    | jq '[.[] | select(.active and .focused) | .rect.height][0] // 900')
if (( output_height < 850 )); then
    margin=40
elif (( output_height < 1100 )); then
    margin=100
else
    margin=180
fi

exec "$HOME/.local/bin/wlogout" \
    --protocol layer-shell \
    --buttons-per-row 5 \
    --column-spacing 18 \
    --row-spacing 18 \
    --margin "$margin" \
    --layout "$HOME/.config/wlogout/layout" \
    --css "$HOME/.config/wlogout/style.css"
